CREATE TABLE `ESPtable2` (
 `id` int(5) NOT NULL AUTO_INCREMENT,
 `PASSWORD` int(5) NOT NULL,
 `SENT_NUMBER_1` int(5) NOT NULL,
 `SENT_NUMBER_2` int(5) NOT NULL,
 `SENT_NUMBER_3` int(5) NOT NULL,
 `SENT_NUMBER_4` int(5) NOT NULL,
 `SENT_BOOL_1` tinyint(1) NOT NULL,
 `SENT_BOOL_2` tinyint(1) NOT NULL,
 `SENT_BOOL_3` tinyint(1) NOT NULL,
 `RECEIVED_BOOL1` int(1) NOT NULL,
 `RECEIVED_BOOL2` int(1) NOT NULL,
 `RECEIVED_BOOL3` int(1) NOT NULL,
 `RECEIVED_BOOL4` int(1) NOT NULL,
 `RECEIVED_NUM1` int(5) NOT NULL,
 `RECEIVED_NUM2` int(5) NOT NULL,
 `RECEIVED_NUM3` int(5) NOT NULL,
 `RECEIVED_NUM4` int(5) NOT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8

--
-- Some values to populate the table `ESPtable2`
--

INSERT INTO `ESPtable2` (`id`, `PASSWORD`, `SENT_NUMBER_1`, `SENT_NUMBER_2`, `SENT_NUMBER_3`, `SENT_NUMBER_4`, `SENT_BOOL_1`, `SENT_BOOL_2`, `SENT_BOOL_3`, `RECEIVED_BOOL1`, `RECEIVED_BOOL2`, `RECEIVED_BOOL3`, `RECEIVED_BOOL4`, `RECEIVED_BOOL5`, `RECEIVED_NUM1`, `RECEIVED_NUM2`, `RECEIVED_NUM3`, `RECEIVED_NUM4`, `RECEIVED_NUM5`, `TEXT_1`) VALUES
(99999, 12345, 327, 1212, 3233, 1313, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Nebune!');